# ⚙️ 7.2 – Numpy Avanzado: Indexación, Ejes y Broadcasting

En este notebook exploraremos las **técnicas avanzadas de Numpy** para manipular arrays multidimensionales: rebanado (slicing), operaciones vectorizadas por ejes y el poderoso concepto de **broadcasting**.

Estas operaciones son fundamentales en la preparación de datos, procesamiento matricial y cálculos científicos.

In [1]:
import numpy as np
print('✅ Notebook 7.2 – Numpy Avanzado cargado correctamente.')

✅ Notebook 7.2 – Numpy Avanzado cargado correctamente.


---
## 🎯 Objetivos
- Usar **slicing e indexación** avanzada sobre arrays multidimensionales.
- Aplicar **operaciones por ejes** (`axis`).
- Comprender y aplicar el **broadcasting** entre arrays de distinta forma.
- Usar máscaras booleanas para filtrado selectivo.
- Combinar, apilar y dividir arrays eficientemente.

---
## 1️⃣ Indexación y slicing

Los arrays Numpy permiten seleccionar subconjuntos de datos usando índices o rangos.

### Ejemplo: selección de submatrices

In [2]:
mat = np.arange(1, 13).reshape(3, 4)
print('Matriz original:\n', mat)
print('\nFila 0 completa:', mat[0, :])
print('Columna 2 completa:', mat[:, 2])
print('Submatriz (filas 0-1, columnas 1-2):\n', mat[0:2, 1:3])

Matriz original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Fila 0 completa: [1 2 3 4]
Columna 2 completa: [ 3  7 11]
Submatriz (filas 0-1, columnas 1-2):
 [[2 3]
 [6 7]]


✅ El slicing devuelve **vistas** del array original, no copias, lo que mejora el rendimiento.

---
## 2️⃣ Operaciones por ejes (`axis`)

El parámetro `axis` controla **la dirección de la operación** dentro del array.

- `axis=0` → opera **por columnas** (vertical).
- `axis=1` → opera **por filas** (horizontal).

In [3]:
x = np.array([[10, 20, 30], [40, 50, 60]])
print('Array:\n', x)

print('\nSuma por columnas (axis=0):', np.sum(x, axis=0))
print('Suma por filas (axis=1):', np.sum(x, axis=1))

Array:
 [[10 20 30]
 [40 50 60]]

Suma por columnas (axis=0): [50 70 90]
Suma por filas (axis=1): [ 60 150]


✅ Usar `axis` correctamente permite realizar cálculos agregados sin bucles, ideal para estadísticas o preprocesado.

---
## 3️⃣ Máscaras booleanas (filtrado)

Podemos aplicar condiciones lógicas directamente sobre arrays para crear **máscaras booleanas**, que filtran los valores que cumplen la condición.

In [4]:
datos = np.array([12, 7, 15, 3, 22, 9])
mask = datos > 10
print('Máscara:', mask)
print('Valores > 10:', datos[mask])

Máscara: [ True False  True False  True False]
Valores > 10: [12 15 22]


✅ Las máscaras permiten filtrar sin bucles y combinarlas con condiciones lógicas: `&`, `|`, `~`.

---
## 4️⃣ 🧩 Ejercicio 1 — Filtrado de temperaturas

Crea un array con temperaturas diarias (30 valores). Filtra y muestra:
- Temperaturas **por encima de 25°C**.
- Número de días con temperatura **entre 20 y 30°C**.

💡 *Pista:* usa operadores lógicos combinados `(a > 20) & (a < 30)`.

In [5]:
# Escribe tu código aquí...

### ✅ Solución propuesta

In [6]:
temp = np.random.randint(10, 40, 30)
print('Temperaturas:', temp)

calor = temp[temp > 25]
rango = temp[(temp >= 20) & (temp <= 30)]

print('\n>25°C:', calor)
print('Entre 20–30°C:', rango)
print('Días en rango:', rango.size)

Temperaturas: [25 28 17 26 24 36 31 17 15 26 16 17 32 26 31 39 39 21 35 32 17 14 23 21
 24 14 22 22 37 36]

>25°C: [28 26 36 31 26 32 26 31 39 39 35 32 37 36]
Entre 20–30°C: [25 28 26 24 26 26 21 23 21 24 22 22]
Días en rango: 12


---
## 5️⃣ Broadcasting

El **broadcasting** permite realizar operaciones entre arrays de **formas diferentes** extendiendo automáticamente los ejes compatibles.

Ejemplo clásico: sumar un vector a cada fila de una matriz.

In [7]:
matriz = np.arange(6).reshape(2, 3)
vector = np.array([10, 20, 30])

print('Matriz:\n', matriz)
print('\nVector:', vector)
print('\nResultado (broadcasting):\n', matriz + vector)

Matriz:
 [[0 1 2]
 [3 4 5]]

Vector: [10 20 30]

Resultado (broadcasting):
 [[10 21 32]
 [13 24 35]]


✅ Broadcasting aplica el vector a cada fila, evitando bucles o repeticiones manuales (`np.tile()` ya no es necesario).

---
## 6️⃣ 🧩 Ejercicio 2 — Normalización de datos

Crea una matriz 3×4 con valores aleatorios enteros (0–100). Normalízala restando la media de cada columna y dividiendo entre su desviación estándar.

💡 *Pista:* usa `np.mean(m, axis=0)` y `np.std(m, axis=0)` combinados con broadcasting.

In [8]:
# Implementa tu código aquí...

### ✅ Solución propuesta

In [9]:
m = np.random.randint(0, 100, (3, 4))
print('Original:\n', m)

media = np.mean(m, axis=0)
desv = np.std(m, axis=0)

norm = (m - media) / desv
print('\nNormalizada:\n', np.round(norm, 2))

Original:
 [[63  7  1 27]
 [ 1  1 20 40]
 [14 70  8 46]]

Normalizada:
 [[ 1.39 -0.61 -1.1  -1.35]
 [-0.94 -0.8   1.32  0.29]
 [-0.45  1.41 -0.21  1.05]]


---
## 7️⃣ Combinación y división de arrays

Podemos concatenar, apilar o dividir arrays fácilmente con las funciones `hstack`, `vstack`, `concatenate`, `split`.

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print('Vertical:\n', np.vstack((a, b)))
print('\nHorizontal:\n', np.hstack((a, b.T)))

Vertical:
 [[1 2]
 [3 4]
 [5 6]]

Horizontal:
 [[1 2 5]
 [3 4 6]]


✅ La combinación de arrays permite construir datasets más grandes o preparar lotes para entrenamiento de modelos.

---
## 🧠 Resumen del notebook

- Indexación y slicing permiten acceder a subconjuntos de datos sin copias.
- `axis` controla el sentido de las operaciones agregadas.
- Las **máscaras booleanas** filtran datos sin bucles.
- El **broadcasting** simplifica operaciones entre matrices de distinto tamaño.
- Se pueden combinar o dividir arrays fácilmente.

💡 Próximo paso → **7.3 – Introducción a Pandas: DataFrames y Series.**